# Generated by Django 5.2.7 on 2025-10-22 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='touristprofile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='services_offered',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_auth_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
